config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users, :controllers => { registrations: 'registrations',
    omniauth_callbacks: "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products
  resources :orders, only: [:index, :create, :show, :destroy]
  resources :shopping_carts, only: [:index] do
    member do
      get 'product/:product_id/add_to_cart', to: 'shopping_carts#add_to_cart', as: 'add_to'
      delete 'product/:product_id/remove_from_cart', to: 'shopping_carts#destroy', as: 'remove_from'
    end
  end

  root to: 'home#index'

  get 'user/:id/orders', to: 'orders#show_user_orders', as: 'user_orders'
  
  scope '/admin' do
    get 'products', to: 'products#index', as: 'admin_products'
    get 'pending_orders', to: 'orders#index', as: 'admin_pending_order'
    get 'orders', to: 'orders#show', as: 'admin_orders'
    get 'confirm_order/:id', to: 'orders#confirm_order', as: 'admin_confirm_order'
  end

  devise_scope :user do
    get "signup", to: "devise/registrations#new"
    get "login", to: "devise/sessions#new"
    get "logout", to: "devise/sessions#destroy"
  end
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  belongs_to :user
  validates_uniqueness_of :user_id
  
  has_many :shopping_cart_products, dependent: :destroy
  has_many :products, through: :shopping_cart_products
  
  scope :most_recent, -> { order(id: :desc) }
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  include ShoppingCartsHelper
  before_action :set_cart

  def index
    @products_in_cart = current_cart.products.most_recent
  end

  def add_to_cart
    add_product_to_cart
  end

  def destroy
    remove_product_from_cart
  end

  private

  def set_cart
    @cart = ShoppingCart.find_by(user_id: current_user.id)
  end
end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
  def current_cart
    @current_cart = ShoppingCart.find_by(user_id: current_user.id) 
  end

  def add_product_to_cart
    @shopping_cart_product = ShoppingCartProduct.create(shopping_cart_id: current_cart.id, product_id: params[:product_id])
    redirect_to shopping_carts_path
  end

  def remove_product_from_cart
    @shopping_cart_product = ShoppingCartProduct.find_by(shopping_cart_id: params[:id], product_id: params[:product_id])
    @shopping_cart_product.destroy
    redirect_to shopping_carts_path
  end

end

app/views/shopping_carts/index.html.erb
<h1>Shopping Cart</h1>

<% unless @products_in_cart.empty? %>
  <table>
    <%= render "products/product_heading" %>
    <% if current_cart %>
      <% @products_in_cart.each do |product| %>
        <tr>
          <td><%= product.description %></td>
          <td><%= product.price %></td>
          <td><%= product.quantity %></td>
          <td><%= product.category.name %></td>
          <td><%= link_to 'Remove from Cart', remove_from_shopping_cart_path( { id: current_cart.id, product_id: product.id } ), method: :delete %></td>
        </tr>
      <% end %>
      <% unless @current_cart.products.empty? %>
        <tr><td><%= link_to 'Checkout', orders_path, method: :post %> </td></tr>
      <% end %>
    <% end %>
  </table>
<% else %>
  <p>Cart is Empty! </p>
<% end %>

<%= link_to 'Back', products_path %>