config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users, :controllers => { registrations: 'registrations',
    omniauth_callbacks: "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products
  resources :orders, only: [:index, :create, :show, :destroy]
  resources :shopping_carts, only: [:index] do
    member do
      get 'product/:product_id/add_to_cart', to: 'shopping_carts#add_to_cart', as: 'add_to'
      delete 'product/:product_id/remove_from_cart', to: 'shopping_carts#destroy', as: 'remove_from'
    end
  end

  root to: 'home#index'

  get 'user/:id/orders', to: 'orders#show_user_orders', as: 'user_orders'
  
  scope '/admin' do
    get 'products', to: 'products#index', as: 'admin_products'
    get 'pending_orders', to: 'orders#index', as: 'admin_pending_order'
    get 'orders', to: 'orders#show', as: 'admin_orders'
    get 'confirm_order/:id', to: 'orders#confirm_order', as: 'admin_confirm_order'
  end

  devise_scope :user do
    get "signup", to: "devise/registrations#new"
    get "login", to: "devise/sessions#new"
    get "logout", to: "devise/sessions#destroy"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2]

  has_one :shopping_cart, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :name, presence: true, length: { maximum: 10 } 
  validates :email, uniqueness: true
  validates :address, presence: true
  validates :password, presence: true, confirmation: true

  enum gender: [:male, :female]

  after_save :create_shopping_cart

  def create_shopping_cart
    @shopping_cart = ShoppingCart.create(user_id: self.id)
  end

  def self.from_omniauth(auth)
    # Either create a User record or update it based on the provider (Google) and the UID   
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.token = auth.credentials.token
      user.expires = auth.credentials.expires
      user.expires_at = auth.credentials.expires_at
      user.refresh_token = auth.credentials.refresh_token
    end
  end
end 

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Google") if is_navigational_format?
      redirect_to '/'
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
    end
  end

  def passthru
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<p>Welcome to Online Shop</p>
<% unless current_user %> 
  <%= link_to 'SignUp', signup_path %>
  <%= link_to 'SignIn', login_path %>
<% end %>

app/views/users/new.html.erb
<%= form_with url: users_path, scope: :user, local: true do |form| %>
   <% if @user.errors.any? %>
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from signing up!:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :phone_number %><br>
    <%= form.text_field :phone_number %>
  </p>

  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>

  <p>
    <%= form.label :address %><br>
    <%= form.text_field :address %>
  </p>

  <p>
    <%= form.radio_button :gender, "male" %>
    <%= form.label :gender_male, "Male" %>
    <%= form.radio_button :gender, "female" %>
    <%= form.label :gender_female, "Female" %>
  </p>

  <p>
    <%= form.label :password %><br>
    <%= form.password_field :password %>
  </p>
  
  <p>
    <%= form.label :password_confirmation %><br>
    <%= form.password_field :password_confirmation %>
  </p>

  <p>
    <%= form.submit :SIGNUP %><br>
  </p>
  
<% end %>