config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users, :controllers => { registrations: 'registrations',
    omniauth_callbacks: "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products
  resources :orders, only: [:index, :create, :show, :destroy]
  resources :shopping_carts, only: [:index] do
    member do
      get 'product/:product_id/add_to_cart', to: 'shopping_carts#add_to_cart', as: 'add_to'
      delete 'product/:product_id/remove_from_cart', to: 'shopping_carts#destroy', as: 'remove_from'
    end
  end

  root to: 'home#index'

  get 'user/:id/orders', to: 'orders#show_user_orders', as: 'user_orders'
  
  scope '/admin' do
    get 'products', to: 'products#index', as: 'admin_products'
    get 'pending_orders', to: 'orders#index', as: 'admin_pending_order'
    get 'orders', to: 'orders#show', as: 'admin_orders'
    get 'confirm_order/:id', to: 'orders#confirm_order', as: 'admin_confirm_order'
  end

  devise_scope :user do
    get "signup", to: "devise/registrations#new"
    get "login", to: "devise/sessions#new"
    get "logout", to: "devise/sessions#destroy"
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :shopping_cart_products, dependent: :destroy
  has_many :shopping_carts, through: :shopping_cart_products
  has_many :order_products, dependent: :destroy
  has_many :orders, through: :order_products
  belongs_to :category

  scope :most_recent, -> { order(created_at: :desc) }

  validates :description, length: { maximum: 500 }
  validates :price, :quantity, presence: true, numericality: true
  has_many_attached :images, dependent: :destroy
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  
  def index
    @products = Product.all.most_recent
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render 'new'
    end
  end
  
  def show
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:description, :price, :quantity, :category_id, images: [])
  end

  def set_product
    @product = Product.find_by(id: params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def check_product_in_cart
    ShoppingCartProduct.find_by(shopping_cart_id: current_cart.id, product_id: @product.id)
  end
end

app/views/products/_form.html.erb
<%= form_for @product  do |form| %>
  <% if @product.errors.any? %>
    <h2>
      <%= pluralize(@product.errors.count, "error") %> prohibited
      from creating the product!:
    </h2>
    <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.label :price %><br>
    <%= form.number_field :price %>
  </p>

  <p>
    <%= form.label :quantity %><br>
    <%= form.number_field :quantity %>
  </p>

  <p>
    <%= form.label :category_name %><br>
    <%= form.collection_select :category_id, Category.all, :id, :name %>
  </p>

  <p>
    <%= form.label :images %><br>
    <%= form.file_field :images, multiple: true %>
  </p>

  <p>
    <%= form.submit ( @product.new_record? ? :ADDPRODUCT : :EDITPRODUCT ) %><br>
  </p>
<% end %>
  

app/views/products/_product_heading.html.erb
<tr>
  <th>Product Desciption</th>
  <th>Product Price</th>
  <th>Product Quantity</th>
  <th>Product Category</th>
  <th>Order Status</th>
</tr>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products</h1>

<table>
  <%= render "product_heading" %>
  
  <% @products.each do |product| %>
    <tr>
      <td><%= product.description %></td>
      <td><%= product.price %></td>
      <td><%= product.quantity %></td>
      <td><%= product.category.name %></td>
      <% unless current_user.is_admin %>
        <td><%= link_to 'Show', product_path(product) %></td>
      <% else %>
        <td><%= link_to 'Show', product_path(product) %></td>
        <td><%= link_to 'Delete', product_path(product), method: :delete, data: { confirm: "Are you sure?" } %></td>
      <% end %>
    </tr>
  <% end %>
</table>
<% if current_user.is_admin %>
  <td><%= link_to 'Create Product', new_product_path %></td>
<% end %>
<%= link_to 'Back', root_path %>

app/views/products/new.html.erb
<h1>Add Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h1>Product <%= @product.id %></h1>

<% if @product.images.attached? %>
  <p><strong>Images : </strong></p><br>
  <% @product.images.each do |image| %>
    <%= image_tag(image) %>
  <% end %>
<% end %>

<table>
  <%= render "product_heading" %>
  <tr>
    <td><%= @product.description %></td>
    <td><%= @product.price %></td>
    <td><%= @product.quantity %></td>
    <td><%= @product.category.name %></td>
  </tr>
</table>

<% if !current_user.is_admin && current_cart %>
  <% unless check_product_in_cart %>
    <%= link_to 'Add to Cart', add_to_shopping_cart_path( { product_id: @product.id } ) %>
  <% else %>
    <p>Product is already in the cart!</p>
  <% end %>
<% else %>
  <%= link_to 'Edit', edit_product_path(@product) %>
<% end %>

<%= link_to 'Back', products_path %>