config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users, :controllers => { registrations: 'registrations',
    omniauth_callbacks: "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products
  resources :orders, only: [:index, :create, :show, :destroy]
  resources :shopping_carts, only: [:index] do
    member do
      get 'product/:product_id/add_to_cart', to: 'shopping_carts#add_to_cart', as: 'add_to'
      delete 'product/:product_id/remove_from_cart', to: 'shopping_carts#destroy', as: 'remove_from'
    end
  end

  root to: 'home#index'

  get 'user/:id/orders', to: 'orders#show_user_orders', as: 'user_orders'
  
  scope '/admin' do
    get 'products', to: 'products#index', as: 'admin_products'
    get 'pending_orders', to: 'orders#index', as: 'admin_pending_order'
    get 'orders', to: 'orders#show', as: 'admin_orders'
    get 'confirm_order/:id', to: 'orders#confirm_order', as: 'admin_confirm_order'
  end

  devise_scope :user do
    get "signup", to: "devise/registrations#new"
    get "login", to: "devise/sessions#new"
    get "logout", to: "devise/sessions#destroy"
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <div class="navbar-header">
        <span><%= link_to "Online Shop", root_path, id: "logo" %></span>
        <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <nav class="navbar-collapse bs-navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? && current_cart && !current_user.is_admin %>
            <li><%= link_to "Shopping Cart", shopping_carts_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "Profile", "#" %></li>
                <li class="divider"></li>
                <li><%= link_to "Sign out", destroy_user_session_path, method: "delete" %></li>
              </ul>
            </li>
          <% elsif user_signed_in? && current_cart && current_user.is_admin %>
            <li><%= link_to "Sign out", destroy_user_session_path, method: "delete" %></li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <p class="navbar-text float-right">
      <% if user_signed_in? && current_cart && !current_user.is_admin %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
        Cart ID : <%= @current_cart.id %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <%= link_to 'Products', products_path, :class => 'navbar-link' %>
        <%= link_to 'Cart', shopping_carts_path, :class => 'navbar-link' %>
        <% unless current_user.orders.empty? %>
          <%= link_to 'My Orders', user_orders_path(current_user.id), :class => 'navbar-link' %>
        <% end %>
      <% elsif user_signed_in? && current_user.is_admin %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <%= link_to 'Products', products_path, :class => 'navbar-link' %>
        <%= link_to 'Pending Orders', admin_pending_order_path, :class => 'navbar-link' %>
        <%= link_to 'Order History', admin_orders_path, :class => 'navbar-link' %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </p>

    <p><br></br></p>

    <%= yield %>
  </body>
</html>